# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'defaultWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(462, 320)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.setup = QtWidgets.QWidget()
        self.setup.setObjectName("setup")
        self.key = QtWidgets.QLabel(self.setup)
        self.key.setGeometry(QtCore.QRect(120, 120, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.key.setFont(font)
        self.key.setAlignment(QtCore.Qt.AlignCenter)
        self.key.setObjectName("key")
        self.label_2 = QtWidgets.QLabel(self.setup)
        self.label_2.setGeometry(QtCore.QRect(30, 180, 391, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.setup)
        self.label.setGeometry(QtCore.QRect(120, 70, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.setup)
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.patientBtn = QtWidgets.QPushButton(self.home)
        self.patientBtn.setGeometry(QtCore.QRect(100, 100, 238, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.patientBtn.setFont(font)
        self.patientBtn.setObjectName("patientBtn")
        self.quickMeasureBtn = QtWidgets.QPushButton(self.home)
        self.quickMeasureBtn.setGeometry(QtCore.QRect(100, 160, 238, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.quickMeasureBtn.setFont(font)
        self.quickMeasureBtn.setObjectName("quickMeasureBtn")
        self.stackedWidget.addWidget(self.home)
        self.patients = QtWidgets.QWidget()
        self.patients.setObjectName("patients")
        self.patientList_2 = QtWidgets.QScrollArea(self.patients)
        self.patientList_2.setGeometry(QtCore.QRect(10, 60, 411, 181))
        self.patientList_2.setWidgetResizable(True)
        self.patientList_2.setObjectName("patientList_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 409, 179))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 411, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.patientList_2.setWidget(self.scrollAreaWidgetContents_2)
        self.patientListTitle_2 = QtWidgets.QLabel(self.patients)
        self.patientListTitle_2.setGeometry(QtCore.QRect(120, 20, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.patientListTitle_2.setFont(font)
        self.patientListTitle_2.setAlignment(QtCore.Qt.AlignCenter)
        self.patientListTitle_2.setObjectName("patientListTitle_2")
        self.patientsCancel = QtWidgets.QPushButton(self.patients)
        self.patientsCancel.setGeometry(QtCore.QRect(330, 250, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.patientsCancel.setFont(font)
        self.patientsCancel.setObjectName("patientsCancel")
        self.stackedWidget.addWidget(self.patients)
        self.joints = QtWidgets.QWidget()
        self.joints.setObjectName("joints")
        self.elbow_2 = QtWidgets.QPushButton(self.joints)
        self.elbow_2.setGeometry(QtCore.QRect(140, 70, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.elbow_2.setFont(font)
        self.elbow_2.setObjectName("elbow_2")
        self.ankle_2 = QtWidgets.QPushButton(self.joints)
        self.ankle_2.setGeometry(QtCore.QRect(140, 120, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ankle_2.setFont(font)
        self.ankle_2.setObjectName("ankle_2")
        self.knee_2 = QtWidgets.QPushButton(self.joints)
        self.knee_2.setGeometry(QtCore.QRect(140, 170, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.knee_2.setFont(font)
        self.knee_2.setObjectName("knee_2")
        self.jointCancel_2 = QtWidgets.QPushButton(self.joints)
        self.jointCancel_2.setGeometry(QtCore.QRect(330, 250, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.jointCancel_2.setFont(font)
        self.jointCancel_2.setObjectName("jointCancel_2")
        self.stackedWidget.addWidget(self.joints)
        self.options = QtWidgets.QWidget()
        self.options.setObjectName("options")
        self.extension_2 = QtWidgets.QPushButton(self.options)
        self.extension_2.setGeometry(QtCore.QRect(140, 110, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.extension_2.setFont(font)
        self.extension_2.setObjectName("extension_2")
        self.label_7 = QtWidgets.QLabel(self.options)
        self.label_7.setGeometry(QtCore.QRect(120, 40, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.flextion_2 = QtWidgets.QPushButton(self.options)
        self.flextion_2.setGeometry(QtCore.QRect(140, 170, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.flextion_2.setFont(font)
        self.flextion_2.setObjectName("flextion_2")
        self.measureTypeCancel = QtWidgets.QPushButton(self.options)
        self.measureTypeCancel.setGeometry(QtCore.QRect(330, 250, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.measureTypeCancel.setFont(font)
        self.measureTypeCancel.setObjectName("measureTypeCancel")
        self.stackedWidget.addWidget(self.options)
        self.angle = QtWidgets.QWidget()
        self.angle.setObjectName("angle")
        self.sendBtn = QtWidgets.QPushButton(self.angle)
        self.sendBtn.setGeometry(QtCore.QRect(110, 160, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.sendBtn.setFont(font)
        self.sendBtn.setObjectName("sendBtn")
        self.angleCancel = QtWidgets.QPushButton(self.angle)
        self.angleCancel.setGeometry(QtCore.QRect(240, 160, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.angleCancel.setFont(font)
        self.angleCancel.setObjectName("angleCancel")
        self.label_4 = QtWidgets.QLabel(self.angle)
        self.label_4.setGeometry(QtCore.QRect(140, 40, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.angle_2 = QtWidgets.QLabel(self.angle)
        self.angle_2.setGeometry(QtCore.QRect(190, 100, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.angle_2.setFont(font)
        self.angle_2.setAlignment(QtCore.Qt.AlignCenter)
        self.angle_2.setObjectName("angle_2")
        self.stackedWidget.addWidget(self.angle)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.key.setText(_translate("MainWindow", "12345"))
        self.label_2.setText(_translate("MainWindow", "Please enter this key into your dashboard"))
        self.label.setText(_translate("MainWindow", "Generated Key:"))
        self.patientBtn.setText(_translate("MainWindow", "Patient List"))
        self.quickMeasureBtn.setText(_translate("MainWindow", "Quick Measurement"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.patientListTitle_2.setText(_translate("MainWindow", "Patient List"))
        self.patientsCancel.setText(_translate("MainWindow", "Cancel"))
        self.elbow_2.setText(_translate("MainWindow", "Elbow"))
        self.ankle_2.setText(_translate("MainWindow", "Ankle"))
        self.knee_2.setText(_translate("MainWindow", "Knee"))
        self.jointCancel_2.setText(_translate("MainWindow", "Cancel"))
        self.extension_2.setText(_translate("MainWindow", "Extension"))
        self.label_7.setText(_translate("MainWindow", "Measurement Type"))
        self.flextion_2.setText(_translate("MainWindow", "Flexion"))
        self.measureTypeCancel.setText(_translate("MainWindow", "Cancel"))
        self.sendBtn.setText(_translate("MainWindow", "Send"))
        self.angleCancel.setText(_translate("MainWindow", "Cancel"))
        self.label_4.setText(_translate("MainWindow", "Measuring..."))
        self.angle_2.setText(_translate("MainWindow", "0"))
